name: Push to Flyte

on:
  workflow_dispatch:
  
jobs:

  push-to-flyte:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Install flytectl
        run: |
          curl -sL https://ctl.flyte.org/install | bash
          ./bin/flytectl sandbox start --source=$(shell pwd)
          ./bin/flytectl config init
          cat /home/runner/.flyte/config.yaml          
          
      - name: Serialize project
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install wheel
          pip install flytekit
          cd project
          mkdir _pb_output
          pyflyte -c /home/runner/.flyte/config.yaml --pkgs train serialize --image qraftaxe/flyte-project-template:46781260 workflows -f _pb_output/
          
      - name: flytectl config init
        run: ./bin/flytectl config init --host=${{ secrets.FLYTE_ENDPOINT }}
     
      - name: Registar serialized project
        run: ./bin/flytectl register files _pb_output/* -p flytesnacks -d development --version ${{ env.short_sha }}
           
      - name: Generate execution spec file
        run: ./bin/flytectl get launchplan -p flytesnacks -d development --version v5 project.train.train_workflow --execFile execution_spec.yaml
        
      - name: Create workflow execution
        run: ./bin/flytectl create execution -p flytesnacks -d development --version v5 --execFile execution_spec.yaml
