name: Push to Flyte

on:
  workflow_dispatch:
  
jobs:

  push-to-flyte:
    runs-on: qraftaxe/flyte-project-template:46781260

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Install flytectl
        run: |
          curl -sL https://ctl.flyte.org/install | bash
          ./bin/flytectl config init --host=${{ secrets.FLYTE_ENDPOINT }}
          ls
 
      - name: Install pyflyte
        run: pip install -r requirements.txt
          
      - name: Serialize project
        run: |
          mkdir _pb_output
          pyflyte --pkgs train serialize --local-source-root ./project --image qraftaxe/flyte-project-template:3c279eae workflows -f ./_pb_output/
     
      - name: Registar serialized project
        run: ./bin/flytectl register files _pb_output/* -p flytesnacks -d development --version ${{ env.short_sha }}
           
      - name: Generate execution spec file
        run: ./bin/flytectl get launchplan -p flytesnacks -d development --version v5 project.train.train_workflow --execFile execution_spec.yaml
        
      - name: Create workflow execution
        run: ./bin/flytectl create execution -p flytesnacks -d development --version v5 --execFile execution_spec.yaml
