name: Push to Flyte

on:
  workflow_dispatch:
  
jobs:

  push-to-flyte:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Install flytectl
        run: |
          curl -sL https://ctl.flyte.org/install | bash 
          echo '${{ secrets.FLYTE_CLIENT_SECRET }}' >> /tmp/flyte_admin_secret
          yq e --inplace '.admin.endpoint = "${{ secrets.FLYTE_ENDPOINT }}"' flyte_config.yaml
          yq e --inplace '.admin.authType = "ClientSecret"' flyte_config.yaml
          yq e --inplace '.admin.clientId = "${{ secrets.FLYTE_CLIENT_ID }}"' flyte_config.yaml
          yq e --inplace '.admin.clientSecretLocation = "/tmp/flyte_admin_secret"' flyte_config.yaml
          cat flyte_config.yaml     
          
      - name: Serialize project
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install wheel
          pip install -r requirements.txt
          mkdir _pb_output
          pyflyte -c flyte_config.yaml --pkgs project.train serialize --local-source-root ./project/ --image qraftaxe/flyte-project-template:46781260 workflows -f _pb_output/

      - name: Registar serialized project
        run: |
          ./bin/flytectl register files _pb_output/* -c flyte_config.yaml -p flytesnacks -d development --version ${{ env.short_sha }}
           
      - name: Generate execution spec file
        run: |
          ./bin/flytectl get launchplan -c flyte_config.yaml -p flytesnacks -d development --version ${{ env.short_sha }} project.train.train_workflow --execFile execution_spec.yaml
        
      - name: Create workflow execution
        run: ./bin/flytectl create execution -c flyte_config.yaml -p flytesnacks -d development --version ${{ env.short_sha }} --execFile execution_spec.yaml
