name: Docker Build & Push

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: docker/build-push-action@v3.1.0
        with:
          file: ./Dockerfile
          tags: qraftaxe/${{ github.event.repository.name }}:${{ env.short_sha }}
          push: true

  push-to-flyte:
    runs-on: qraftaxe/${{ github.event.repository.name }}:${{ env.short_sha }}

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Install flytectl
        run: |
          curl -sL https://ctl.flyte.org/install | bash
          ./bin/flytectl config init --host=${{ secrets.FLYTE_ENDPOINT }}
 
#       - name: Install pyflyte
#         run: pip install -r requirements.txt
          
      - name: Serialize project
        run: |
          mkdir _pb_output
          pyflyte --pkgs train serialize --local-source-root ./project --image qraftaxe/${{ github.event.repository.name }}:${{ env.short_sha }} workflows -f ./_pb_output/
     
      - name: Registar serialized project
        run: ./bin/flytectl register files _pb_output/* -p flytesnacks -d development --version ${{ env.short_sha }}
           
      - name: Generate execution spec file
        run: ./bin/flytectl get launchplan -p flytesnacks -d development --version v5 project.train.train_workflow --execFile execution_spec.yaml
        
      - name: Create workflow execution
        run: ./bin/flytectl create execution -p flytesnacks -d development --version v5 --execFile execution_spec.yaml
