# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV 
