# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
        
